services:
  ipfsserver:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-host
    ports:
     - 4001:4001
     - 5001:5001
    volumes:
      - /home/eoin/projects/college/2022/nci2022/ipfs/staging:/export
    networks:
     - labnetwork
  nci_erc20:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - labnetwork
networks:
  labnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24